jari_jari=float(input(""))
tinggi = float(input(""))
phi=22.0/7.0
Volume= phi*(jari_jari*jari_jari)*tinggi
print("Volume = ",format(Volume,'.2f'))
Luas = 2*phi*jari_jari*(jari_jari+tinggi)
print("Luas = ",format(Luas,'.2f'))
Keliling = 2*phi*jari_jari
print("Keliling = ",format(Keliling,'.2f'))